name: 'Create Release'

on:
  push:
    branches: [ $default-branch ]
  workflow_call:
    inputs:
      default-agent:
        required: true
        type: string
        default: self-hosted
      version:
        required: false
        type: string
      release-type:
        # Get more information official docs: https://github.com/marketplace/actions/release-please-action#release-types-supported
        required: true
        type: string
        default: simple
      pre-release:
        required: true
        type: boolean
        default: true
      package-name:
        required: true
        type: string
        default: simple
    secrets:
      github-pat:
        required: true
  
jobs:
  # create-tag-manual:
  #   runs-on: ${{ inputs.default-agent }}
  #   if: ${{ inputs.version != null }}
  #   steps:
  #     - uses: actions/checkout@v3

  release:
    runs-on: ${{ inputs.default-agent }}
    #if: ${{ inputs.version != null }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: ${{ inputs.release-type }}
          package-name: ${{ github.repository }}-${{ github.sha }}
          #prerelease: ${{ inputs.pre-release }}
          changelog-path: CHANGELOG.md
          token: ${{ secrets.github-pat }}
