name: 'Build Flutter Web'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      default-agent:
        required: true
        type: string
        default: self-hosted
      working-directory:
        required: true
        type: string
        default: .
      flutter-version:
        required: true
        type: string
        default: 3.3.0
      upload-name:
        required: true
        type: string
        default: build-artifacts
      upload-path:
        required: true
        type: string
        default: .
      upload-retention:
        required: true
        type: number
        default: 7

jobs:
  build:
    runs-on: ${{ inputs.default-agent }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update && sudo apt-get install jq -y

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
          channel: "stable"
          architecture: x64

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
      # - run: flutter test --machine > test-results.json
      # - uses: dorny/test-reporter@v1.4.2
      #   with:
      #     name: test-results
      #     path: test-results.json
      #     reporter: flutter-json
      # - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
      #   with:
      #     min_coverage: 0
      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.upload-name }}
          path: ${{ inputs.upload-path }}
          retention-days: ${{ inputs.upload-retention }}
