name: 'Build Flutter Web'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      default-agent:
        required: true
        type: string
        default: self-hosted
      working-directory:
        required: true
        type: string
        default: .
      flutter-version:
        required: true
        type: string
        default: 3.3.0
      extra-params:
        required: false
        type: string
      upload-name:
        required: true
        type: string
        default: build-artifacts
      upload-path:
        required: true
        type: string
        default: .
      upload-retention:
        required: true
        type: number
        default: 7

jobs:
  build:
    runs-on: ${{ inputs.default-agent }}
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}
          channel: "stable"

      - run: flutter upgrade

      - run: flutter config --enable-web

      - run: flutter clean

      - run: flutter pub get

      - run: flutter build web --release --web-renderer html ${{ inputs.extra-params }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.upload-name }}-${{ inputs.environment }}
          path: ${{ inputs.upload-path }}
          retention-days: ${{ inputs.upload-retention }}
